### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by SkyLeite** [briefercloud/briefer#10]
Hello!

Thank you for this project. It seems to be everything I've always wanted Excel to be :)

Would it be possible to publish documentation for the API? While I understand that the Slack and Email integrations are enterprise-only, it'd be great if for personal use I was able to write integrations for other services like [n8n](https://n8n.io/) and [pushover](https://pushover.net/).

**Comment by vr-varad** [comment]
@lucasfcosta Could u assign me this issue, I would like to work on this issue!!

**Comment by lucasfcosta** [comment]
Thanks for the issue @SkyLeite!

Hey @vr-varad before we get to that I think it would be interesting to figure out what exactly the API docs would be. Otherwise I think this issue would extend indefinitely as there will always be new endpoints.

Let's start with this:

* We need concrete examples of what kinds of tasks you'd like to accomplish with the API so we can figure out which endpoints we need more thorough documentation for
* Additionally, we also need to figure out what changes will be needed to allow folks to call those APIs - right now the authentication mechanisms aren't really ideal for external use

How about we start with these two?

**Comment by vr-varad** [comment]
Sure, I will share with the plan before making any changes.
@lucasfcosta

**Comment by vieiralucas** [comment]
@SkyLeite thank you so much for this issue.

I'm not sure about n8n, but you can easily integrate with pushover using python and env vars, I'm happy to show you how these could work if you want.

I would like to encourage you to open more specific issues like "add integration with pushover" next time. Then we can discuss how those can be achieve inside briefer or if we can/want to implement a more native integration.

Now, I think it is too early to talk about an generic API for integrations. If you ever need any help integrating Briefer with other software feel free to open issues or send a message to the community in Slack.

**Comment by SkyLeite** [comment]
That makes sense! I don't really have a use-case in mind yet, I just figured it would be generally useful to have the internal API be documented somewhere. Totally down to opening more specific issues in the future though. Thanks for considering :)
