### ISSUE TITLE
[feature] Support rendering images with Markdown in text cells

### ISSUE THREAD

**Issue by felipbizz** [briefercloud/briefer#102]
Using markdown in the jupyter notebook it is possible to insert a local image using "! [title] (briefer_image.png)" and when I run this markdown cell it renders in the notebook displaying the image. 

As in the example below: 
![image](https://github.com/user-attachments/assets/3c65ef6c-f717-4ba9-80dd-14784a67c412)

Is there any way to do this in Briefer today? 

It would be a very interesting feature to build a more visual storytelling using external images or videos and not just the graphs generated by the data in the briefer itself

**Comment by marquesine** [comment]
Hey, @felipbizz,

When I try to use Markdown syntax for adding images on Briefer's text cells, the images reference seem to be broken. However when I copy and past an image on a cell it works.

Have you tried that?

I agree that the optimal solution would be for adding images just like how we do here in GitHub (paste an image -> generate an upload link -> transform it into md syntax).

**Comment by vieiralucas** [comment]
Just for clarification the markdown editor in Briefer is different from what we have here in Github because you don't write markdown source that gets transform into html. Briefer Rich Text blocks are a "WYSIWYG" editor powered by [Tiptap](https://tiptap.dev).

That said we could have better support for images, dropping images in the Rich Text Block should work, just like pasting them in, I consider this a bug and have opened a issue for this (#119).
