### ISSUE TITLE
Add Databricks SQL Connector

### ISSUE THREAD

**Issue by DanFitzgibbon** [briefercloud/briefer#133]
(Am interested in developing this on my own but any help is of course very welcome!)

For clarity's sake: the idea is to have a Databricks Warehouse connector.

**Comment by lucasfcosta** [comment]
Hey @DanFitzgibbon! Thanks a lot for the issue - we _definitely_ want to have a DataBricks Warehouse connector and would love your contribution.

If you're interested in trying it out, please have a look at #127  and #107 - they implement connectors for Snowflake and MSSQL so that could be a good inspiration.

Implementing a connector is all about following the existing patterns - it isn't something that's really that hard (in terms of complexity) tbh

Lmk what you think - happy to assign this to you if you want

**Comment by DanFitzgibbon** [comment]
Heya, [PR ready for review](#139)! conscious there's another PR adding MonetDB - if you want to merge that given it's an older issue, I'll just rebase my branch with main once it's merged.
