### ISSUE TITLE
Help in order to connect to an Oracle Cloud Instance Database

### ISSUE THREAD

**Issue by fcjbispo** [briefercloud/briefer#136]
Hi, guys.

I need some help in order to connect my local docker briefer instance to my Oracle Database hosted in Oracle Cloud. I already create a income rule to allow access from my host ip but I'm not sure what I need to put on the briefer connection fields in order to stablish the connection. I've tried to use the host, port and service names found on my tns_names.ora from the wallet by no success at all. Thanks in advance.

**Comment by lucasfcosta** [comment]
Hey @fcjbispo thanks for the issue!

I'd love to help you out here. 

It turns out that Oracle databases can be a bit confusing and there are multiple ways of setting them up, so I'd recommend that [we book a call using this link and look through it synchronously](https://calendly.com/lucasfcosta/1-1-lucas-blocks).

Would that work?

**Comment by fcjbispo** [comment]
Hi Lucas,

Thanks for your support. I will appreciate your help for sure. I will look at the available dates and pick one that be suitable for us. I'm at Brazil/Brasilia Time.

I heard somewhere you' re brazilian too. If is it so, may we chat in Portuguese?

Thanks for your time.

Francisco Bispo.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vieiralucas** [comment]
@fcjbispo I'll close that one in favor of #143. Thank you for your time helping us figure out the problem here.
