### ISSUE TITLE
How to install without Docker

### ISSUE THREAD

**Issue by andrader** [briefercloud/briefer#20]
Hi. Is there a way to test it local without installing Docker?

docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

**Comment by KiitoNahari** [comment]
As i know, it needs docker to run. the pip push the docker image for you and set it up.

**Comment by KiitoNahari** [comment]
well. its right. on the guide says that need docker to work.

**Comment by vieiralucas** [comment]
Hello @andrader, thank you for your issue, we would like to support that in the future but currently we are far from being able to.
The problem is that we have dependencies on `python`, `nodejs` and `postgresql`. We think that asking the user to just have docker instead of having to explain how to install all those dependencies in it's machine and set them up is much easier.
If for some reason, you can't install docker let me know, I would like to learn why.
