### ISSUE TITLE
[feature]: use default GCP authentication

### ISSUE THREAD

**Issue by guissalustiano** [briefercloud/briefer#238]
Hi, we are running briefer on GCP and would like to manage the permission with a service account instead using a file.

Currently, briefer always uses the credential file
https://github.com/briefercloud/briefer/blob/3799057d2588ded39eaab641d20063cee30ca3d0/apps/api/src/python/query/bigquery.ts#L119-L124

but I think we should not require the credential file and try with [default credentials](https://cloud.google.com/bigquery/docs/samples/bigquery-client-default-credentials#bigquery_client_default_credentials-python).

I would like to work on that, but I first open the PR to check if this feature would be accepted and if there is any suggestion on how to implement that. Thanks!

**Comment by lucasfcosta** [comment]
Hey @guissalustiano, thank you so much for opening this issue!

I really like this idea, but my main concern here is _why_ that would be necessary. I thought that we'd load the service account anyway when querying from the jupyter pod so we wouldn't need to authenticate through the pod itself. Not sure if GCP has a particular setting to handle scenarios like this.

Ideally, we should be able to run the query without attaching the SA to the pod because then it will run in the exact same way when running outside of K8S.

I'll CC @vieiralucas in here so he can chime in as well.

---

If we do decide to go ahead, IMO the best way to handle this would be to add a toggle on the BigQuery form that says something like `Assign this service account to my Jupyter environment`.

When that's toggled we should patch the existing jupyter pod within the cluster so it uses the service account. Every query goes through that particular pod, not through the API.

A few attention points here:

* We should ideally detect whether people are deploying it on K8S and only show the checkbox/patch the jupyter pod if people are running within K8S
* The helm chart should include the necessary permissions to do this patching, but only if a particular value is set to `true`

Let's wait a bit for @vieiralucas before we move ahead here

**Comment by lucasfcosta** [comment]
@guissalustiano just discussed this with @vieiralucas on Slack.

We came to the conclusion that the right way to solve this is to fix the bug which prevents real errors from showing up when people connect a data source.

In this case, you'd have seen a message saying something like `lacks permissions XYZ`.

Do you want to go ahead with a PR? We're happy to fix this on our end too if you're busy. Otherwise, happy to help you contribute.

FYI the reason we decided to do this is to streamline the way the software works so it always works the same way instead of creating a special case and attaching a service account to the pod.

Wdyt?
