### ISSUE TITLE
Settings is not showing an option to set the OPEN_AI_KEY

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#29]
Please confirm this is still happening when you run Briefer's container as per the `README.md` instructions.

Apparently, there is no option to add an `OPEN_AI_KEY` within the `Settings` screen. There should be a row there where an Admin can add an OpenAI key so they can use the "Edit with AI features".

Help on this would be much appreciated, and it's a good first issue.

If you can't reproduce this, please let me know.

**Comment by Shivangi020** [comment]
I would like to work on it. Could someone assign this issue to me?

**Comment by lucasfcosta** [comment]
@Shivangi020 yes please! As a quick note, this is pretty urgent for us, so we'll probably submit a PR on Monday to fix it. Don't worry if you can't get a PR up by then - I appreciate the willingness to contribute in any way

This is quite a high-priority one so that's why I'm saying this.

**Comment by vieiralucas** [comment]
Hi @Shivangi020, fyi, the problem most likely is in [this line](https://github.com/briefercloud/briefer/blob/d9e513d3499671d169752e856b54bb8cfbfd4c8b/apps/api/src/properties.ts#L7).

Instead of conparing to `undefined` we should check if it is `true` **AND** that there is no `      workspace?.secrets?.openAiApiKey`

I think changing that function to something like this should fix this issue:
```typescript
export default async function properties(): Promise<Properties> {
  const workspace = await prisma().workspace.findFirst()
  const needsSetup = workspace === null

  let requiresOpenAiKey = false
  if (workspace && config().ENABLE_CUSTOM_OAI_KEY) {
    const ws = await getWorkspaceWithSecrets(workspace.id)
    if (!ws) {
      throw new Error(`Workspace(${workspace.id}) not found`)
    }

    requiresOpenAiKey = ws.secrets?.openAiApiKey === null
  }

  return {
    needsSetup,
    requiresOpenAiKey,
    disabledAnonymousTelemetry: config().DISABLE_ANONYMOUS_TELEMETRY,
  }
}

```

Do you want to try that?

**Comment by Shivangi020** [comment]
Hi @vieiralucas 
Thank you for assigning me this task. Unfortunately, I’ve been having trouble setting up Docker (very new to Docker ), and I’m unable to see my local changes on the server. I did find that there was an issue with the properties, but I haven’t been able to resolve it yet. Apologies for the delay—please let me know if you have any suggestions on how to proceed.

**Comment by Shivangi020** [comment]
I followed the contribution.md guidelines, and when running yarn dev, I encountered this error
![image](https://github.com/user-attachments/assets/497ef0a1-4d6f-4e8b-9610-289430eee45b) 
for docker this is the error
while interpolating services.ai.environment.OPENAI_API_KEY: required variable OPENAI_API_KEY is missing a value: error

**Comment by vieiralucas** [comment]
Hi @Shivangi020 

> Hi @vieiralucas Thank you for assigning me this task. Unfortunately, I’ve been having trouble setting up Docker (I'm very new to Docker ), and I’m unable to see my local changes on the server. I did find that there was an issue with the properties, but I haven’t been able to resolve it yet. Apologies for the delay—please let me know if you have any suggestions on how to proceed.

It looks like you're trying to spin up the "production" compose.
Make sure to either run `./start-dev.sh` or `docker compose -f docker-compose.dev.yaml up`





> I followed the contribution.md guidelines, and when running yarn dev, I encountered this error ![image](https://private-user-images.githubusercontent.com/72787457/367843852-497ef0a1-4d6f-4e8b-9610-289430eee45b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTkzNjksIm5iZiI6MTcyNjUxOTA2OSwicGF0aCI6Ii83Mjc4NzQ1Ny8zNjc4NDM4NTItNDk3ZWYwYTEtNGQ2Zi00ZThiLTk2MTAtMjg5NDMwZWVlNDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDIwMzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YjMxMTM0ZDc5N2MzZWMzODU2ZWJkYzVhZDllNzQyMzkwMTlkYWM1YWE1YmIwYjliZTcxYTlmNmZkYzY0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cbaTtoNbvp8z-Ah4TvVNF1TxlpYLO7hqeNmjnAwKhuo) for docker this is the error while interpolating services.ai.environment.OPENAI_API_KEY: required variable OPENAI_API_KEY is missing a value: error
> 
> Since the environment variables involve OpenSSL, I thought the problem might be related to that, but OpenSSL is installed on my system. Even though I might not be able to create a PR for this issue, I would like to know what I am doing wrong.

The `start-dev.sh` script should create the necessary env variables. But if you keep seeing this screen, make sure that you have a `apps/web/.env` file with the following contents:
```
NODE_ENV=development
NEXT_PUBLIC_API_URL='https://localhost:8080'
NEXT_PUBLIC_API_WS_URL='wss://localhost:8080'
NEXT_PUBLIC_PUBLIC_URL='https://localhost:4000'
```

Notice, the `./start-dev.sh` script will only bring up the dependencies (`jupyter_server` and `postgres`). You'll still need to run `yarn dev`.

Please don't hesitate to keep replying here if you still are unable to run locally in dev mode, if you prefer you can reach me at our slack and I can assist you synchronously.

Don't feel sorry for not being able to run locally, helping you being able to do that is very important for us so that we can improve the contributing docs.
