### ISSUE TITLE
[feature] add support to s3

### ISSUE THREAD

**Issue by dverzolla** [briefercloud/briefer#79]
The current  jupyter's image notebook and the integration with briefer points the "Files" resource to `/home/jupyteruser`. 
Adding support to s3 would avoid creating persistent storage, making briefer even more "container friendly". While implementing s3, consider using AWS SDK, so all authentication methods will be available (access/secret, assumed role etc.).

**Comment by lucasfcosta** [comment]
Hey @dverzolla! Love this idea - we're thinking about adding it to the cloud/enterprise versions only though because the integrations are a significant selling point for those versions.

Also, right now people can already use Python blocks + environment variables to connect to S3, so it's an okay workaround - and after we add reusable components it'll be even easier - it's just the native integration we're thinking of reserving to cloud.

I'll close this for now but just want to highlight that I deeply appreciate your willingness to contribute so far! We'll have a look at those K8S manifests soon!
